### ISSUE TITLE
Can we make changes on the Client side?

### ISSUE THREAD

**Issue by ambuje** [badsyntax/mailinabox-ui#76]
Hi 
A very cool project and kudos to your skills.
Do you know how can I make changes at the user side  <domain>/mail is where the user side login page opens. Do you know the location of the source file?

Thanks

**Comment by badsyntax** [comment]
Hi and thanks! Not sure I'm following, what changes do you want to make?

**Comment by ambuje** [comment]
https://52.188.110.100/mail/ ,
How can I make changes to this HTML file. Do you have an Idea about the source file 

Thanks

**Comment by badsyntax** [comment]
That is the roundcube web interface and entirely unrelated to this project. This project is a reskin of the mailinabox admin, not the roundcube interface.
